# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Learn, write and share!
tagline:          '(by <a href="https://twitter.com/munilvc" target="_blank">@munilvc</a>)'
description:      'My personal site to share lessons learned while working on Software and enjoying Life.'
url:              http://munilvc.github.io
paginate:         5

author:
  name:           'Felipe Vega'
  url:            https://twitter.com/munilvc

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/munilvc
